package com.example.eksamensprojekt.Model.Enums;

public enum KmPrMonth {
  FIFTEEN_HUNDRED,
  SEVENTEEN_HUNDRED_AND_FIFTY,
  TWO_THOUSAND,
  TWO_THOUSAND_FIVE_HUNDRED,
  THREE_THOUSAND,
  THREE_THOUSAND_FIVE_HUNDRED,
  FOUR_THOUSAND,
  FOUR_THOUSAND_FIVE_HUNDRED
}
